# Generated by Django 3.1.3 on 2020-11-28 19:32

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=30)),
                ('vat_number', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20)),
                ('contact_person_email', models.CharField(blank=True, max_length=254)),
                ('registration_date', models.DateField(auto_now=True)),
                ('contract', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'client',
            },
        ),
    ]
