# Generated by Django 3.1.3 on 2020-12-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201203_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contract',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
