# Generated by Django 3.1.3 on 2020-12-09 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201203_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHighlight',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_always', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('content_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
            ],
            options={
                'verbose_name': 'content',
            },
        ),
    ]
