# Generated by Django 3.1.3 on 2020-12-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contenthighlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenthighlight',
            old_name='content_uuid',
            new_name='content',
        ),
    ]
