# Generated by Django 3.1.3 on 2020-12-10 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201209_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenthighlight',
            options={'verbose_name': 'highlight'},
        ),
        migrations.CreateModel(
            name='ContentSibling',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_uuid', to='core.content')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_uuid', to='core.content')),
            ],
            options={
                'verbose_name': 'content',
            },
        ),
    ]
