# Generated by Django 3.1.3 on 2020-12-19 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201210_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUpselling',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
            ],
            options={
                'verbose_name': 'upselling',
                'verbose_name_plural': 'upselling',
            },
        ),
    ]
