# Generated by Django 3.1.3 on 2020-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contentupselling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('cliend_uuid', models.UUIDField()),
                ('upselling_uuid', models.UUIDField()),
                ('highlight_uuid', models.UUIDField()),
                ('is_parent', models.BooleanField()),
                ('is_institutional', models.BooleanField()),
                ('active_highlight', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'content_card_view',
                'managed': False,
            },
        ),
    ]
