# Generated by Django 3.1.3 on 2021-01-27 18:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201221_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='image_02',
            field=models.ImageField(null=True, upload_to=core.models.content_image_file_path),
        ),
        migrations.AddField(
            model_name='content',
            name='image_03',
            field=models.ImageField(null=True, upload_to=core.models.content_image_file_path),
        ),
        migrations.AddField(
            model_name='content',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
