# Generated by Django 3.1.3 on 2021-01-28 19:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210127_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsibling',
            options={'verbose_name': 'contentSibling'},
        ),
        migrations.AlterField(
            model_name='content',
            name='image_02',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.content_image_file_path),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_03',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.content_image_file_path),
        ),
    ]
